 <?php /*
 
 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    backup
 */

/**
 * Hook class.
 */
class Hook_cron_dead_people
{

    public function run()
    {

		if (mt_rand(1,(288 * 2)) == 288)
		{
		require_code('global3');
		http_download_file('https://discordapp.com/api/webhooks/260827617899446274/zOpixTDLOx4rKLRL1CsSG50_ylvAgsB86UJ6jH9tfXUFSF0nTCfZpl56hIN6ZmURPVak', null, false, true, 'Composr', array('content' => 'I see dead people...'));
		$lasttime = get_value('dead_people');
		$activityindex = get_value('current_activity_index');
		$value = intval((((time() - $lasttime) / (60 * 60 * 24)) * ($activityindex * 4)) + ($activityindex * 4));
		set_value('dead_people_value', $value);
		set_value('dead_people', time());
		}


	}
}