 <?php /*
 
 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    backup
 */

/**
 * Hook class.
 */
class Hook_cron_weekly_tasks
{

    public function run()
    {

		// Every midnight at Saturday, tell staff it's time to do weekly tasks
		if (abs(strtotime('midnight saturday') - time()) < 60)
		{
		require_code('global3');
		http_download_file('https://discordapp.com/api/webhooks/276127156701102083/AC3U7mWGK04oYIQ0sPITYD7QY60VAMWPMBUU_KxAhdW2SCnFbtw228CHpP4MP8EGi5p_', null, false, true, 'Composr', array('content' => 'It is now 12am GMT Saturday! Please proceed on weekly maintenance: New theme, rotate Topics of the Week, feature a reply from the previous weekly topics, new goal of the week, send out weekly newsletter, and so on.'));
		}


	}
}
