 <?php /*
 
 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    backup
 */

/**
 * Hook class.
 */
class Hook_cron_yang_worth
{

    public function run()
    {

// Due to the complexity, it will only be calculated once every 15 minutes.
		$_last_run = get_value('last_time_cron__yang_worth', null, true);
       	$last_run = is_null($_last_run) ? 0 : intval($_last_run);
        if ($last_run < time() - (60 * 15)) {
			set_value('last_time_cron__yang_worth', strval(time()), true);
			
			require_code('points');
			$yang = 0;
			$backing = 0;
			
			$members = $GLOBALS['SITE_DB']->query_select('f_members', array('id'), null);
			foreach ($members as $member)
			{
				$yang += available_points($member['id']);
			}

			$backing += $GLOBALS['SITE_DB']->query_select_value_if_there('transactions', 'SUM(t_amount)', array('t_currency' => 'USD', 't_status' => 'Completed'));

			$yangworth = ($yang != 0) ? (($backing / $yang) * 1000) : 0;
			set_value('yang_worth', strval(float_format($yangworth)));

		}
	}
}