<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    tickets
 */

/**
 * Hook class.
 */
class Hook_change_detection_feedback
{
    /**
     * Run function for change_detection hooks. They see if their own something has changed in comparison to sample data.
     *
     * @param  string $data The sample data, serialised and then MD5'd
     * @return boolean Whether the something has changed
     */
    public function run($data)
    {
		require_code('topics');
		$ob = new CMS_Topic();
        $id = get_param_integer('id2', null);
        if ($id === null || $id === 0)
			return 0;
        $page = get_param_string('page2', null);
        $start = get_param_integer('start_comments', 0);
        $num_to_show_limit = get_param_integer('max_comments', intval(get_option('comments_to_show_in_thread')));
        
		if (get_forum_type() != 'cns') {
            warn_exit(do_lang_tempcode('NO_CNS'));
        } else {
            cns_require_all_forum_stuff();
        }
        if (!$ob->load_from_topic($id, $num_to_show_limit, $start, false)) {
            attach_message(do_lang_tempcode('MISSING_FORUM', escape_html($forum_name)), 'warn');
        }
        require_code('cns_topicview');
        require_code('crypt');
        return md5(serialize($ob->total_posts)) != $data;
	}
}
