<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/*EXTRA FUNCTIONS: openssl_.**/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Determine whether the necessary PHP extensions to support encryption are available. For normal use, you should probably use is_encryption_enabled() instead.
 *
 * @return boolean Encryption available?
 */
function is_encryption_available()
{
    return function_exists('openssl_pkey_get_public');
}

/**
 * Determine whether encryption support is available and enabled in the site's preferences, and the keys are in place.
 *
 * @return boolean Encryption enabled?
 */
function is_encryption_enabled()
{
    static $enabled = null;
    if ($enabled === null) {
        $public_key = str_replace('{file_base}', get_file_base(), get_option('encryption_key'));
        $private_key = str_replace('{file_base}', get_file_base(), get_option('decryption_key'));
        $enabled = ((function_exists('openssl_pkey_get_public')) && ($public_key != '') && ($private_key != '') && (file_exists($public_key)) && (file_exists($private_key)));
    }
    return $enabled;
}

/**
 * Encrypt some data using asymmetric encryption and the site's public key. This will return the original data if encryption is disabled. It will add a magic marker to the start of the returned string to show it's been encrypted.
 * A fatal error will occur if the public key cannot be found, or if encryption fails for whatever reason.
 * Note that this will blindly re-encrypt data which has already been encrypted. You should check data with is_data_encrypted() first.
 *
 * @param  string $data Data to be encrypted
 * @return string Encrypted data, with magic marker
 */
function encrypt_data($data, $passcode = false)
{
	
    require_lang('encryption');

    if (!is_encryption_enabled()) {
        return $data;
    }
    if ($data == '') {
        return $data;
    }
    if (is_data_encrypted($data)) {
        return $data;
    }

    if (!function_exists('openssl_pkey_get_public')) {
        return $data;
    }
    if (!function_exists('openssl_public_encrypt')) {
        return $data;
    }
    
    $iv = openssl_random_pseudo_bytes(16);

    $id = uniqid('', false);

    /* See http://php.net/manual/en/function.openssl-pkey-get-public.php */
    $key = openssl_pkey_get_public('file://' . str_replace('{file_base}', get_file_base(), get_option('encryption_key')));
    if ($key === false) {
        attach_message(do_lang_tempcode('ENCRYPTION_KEY_ERROR'), 'warn');
        return $data;
    }

    if (!openssl_seal($data, $sealed, $ekeys, array('file://' . str_replace('{file_base}', get_file_base(), get_option('encryption_key'))), "AES256", $iv)) {
        attach_message(do_lang_tempcode('ENCRYPTION_ERROR'), 'warn');
        return $data;
    }

    if ($passcode)
	{
		require_code('crypt');

      		$member_id = get_member();
        	$to_name = $GLOBALS['FORUM_DRIVER']->get_username(get_member());

        	$email_address = $GLOBALS['FORUM_DRIVER']->get_member_row_field(get_member(), 'm_email_address');
        	if (is_null($email_address)) {
        	    fatal_exit(do_lang_tempcode('INTERNAL_ERROR'));
        	}

		$from_email = get_option('website_email');
		$from_name = get_option('site_name');
        	$extra_cc_addresses = array();
        	$extra_bcc_addresses = array();

        	require_code('mail');
       	 	$attachments = array();
		$size_so_far = 0;

		$message = 'Greetings ' . $to_name . ',

You have recently used the pencrypt tag on The Lovinity Community+. The pencrypt tag, unlike the encrypt tag, does not store the random key used to encrypt your content. You will need to use the decryption key in this email to decrypt the content.

ID of the encrypted text: ' . $id . '

Decryption key to decrypt the text: ' . base64_encode($ekeys[0]);

		mail_wrap($from_name . ' - Decryption key for encrypted message ID ' . $id, $message, array($email_address), $to_name, $from_email, $from_name, 3, $attachments, false, get_member(), false, false, false, 'MAIL', null, $extra_cc_addresses, $extra_bcc_addresses, null);
		$ekeys[0] = '';
	}

    
		$GLOBALS['SITE_DB']->query_insert('iv', array(
            	'ID' => $id,
            	'iv' => base64_encode($iv),
            	'passkey' => base64_encode($ekeys[0]),
		'passcode' => $passcode ? '1' : '0',
       		));    
       		
    return '(Encrypted!)(' . $id . ')' . base64_encode($sealed);
}

/**
 * Determine if some data has already been encrypted: i.e. if it has a magic encryption marker.
 *
 * @param  string $data Data to check
 * @return boolean Encrypted?
 */
function is_data_encrypted($data)
{
    if (!is_string($data)) {
        return false;
    }
    return (substr($data, 0, 12) == '(Encrypted!)');
}

function remove_id($data, &$id)
{
    if (!is_string($data)) {
        return false;
    }
    $id = substr($data, 1, 13); 
 return substr($data, 15);
}

function needs_passcode($data)
{
$id = '';
$data = base64_decode(remove_id(remove_magic_encryption_marker(str_replace('<br />', '', $data)), $id));
$passcode = $GLOBALS['SITE_DB']->query_select_value_if_there('iv', 'passcode', array('ID' => $id));
return $passcode;
}

/**
 * Remove the magic encryption marker from some data. This should be used if the data is to be displayed or presented for editing, but not if it's to be put in the database.
 * If the data does not have a magic encryption marker, the original string will be returned.
 *
 * @param  string $data Data
 * @return string Data, without the magic marker
 */
function remove_magic_encryption_marker($data)
{
    if (!is_data_encrypted($data)) {
        return $data;
    }
    return substr($data, 12);
}

/**
 * Decrypt data using asymmetric encryption, and the site's private key (as unlocked by the given passphrase).
 * A fatal error will occur if the passphrase is empty, the key cannot be found, or if decryption fails for whatever reason.
 *
 * @param  string $data Data to be decrypted
 * @param  string $passphrase Passphrase to unlock the site's private key
 * @return string Decrypted data
 */
function decrypt_data($data, $passphrase = '82f803c1875974c0c06ffd5ec1d39192', $htmlwrap = false, $passcode = null, $make_string = true)
{
    require_lang('encryption');
    require_code('tempcode');

    if ($data == '') {
        return '';
    }

    if (!function_exists('openssl_pkey_get_private')) {
        return '';
    }
    if (!function_exists('openssl_private_decrypt')) {
        return '';
    }

    // Check the passphrase isn't empty (if it is legitimately empty, we're doing the site a favour by bailing out)
    if ($passphrase == '') {
        attach_message(do_lang_tempcode('ENCRYPTION_KEY_ERROR'), 'warn');
        return '';
    }

    // Remove the magic encryption marker and base64-decode it first
    $data = base64_decode(remove_id(remove_magic_encryption_marker(str_replace('<br />', '', $data)), $id));

    $keys = $GLOBALS['SITE_DB']->query_select('iv', array('*'), array('ID' => $id));
    foreach ($keys as $akey)
    {
    $iv = base64_decode($akey['iv']);
    $passkey = base64_decode($akey['passkey']);
    $_passcode = $akey['passcode'];
    } 

    $key = openssl_pkey_get_private(array('file://' . str_replace('{file_base}', get_file_base(), get_option('decryption_key')), $passphrase));
    if ($key === false) {
        attach_message(do_lang_tempcode('ENCRYPTION_KEY_ERROR'), 'warn');
        return '';
    }

	if ($_passcode == 1)
		$passkey = base64_decode($passcode);

        if (!openssl_open($data, $output, $passkey, $key, "AES256", $iv)) {
            attach_message(do_lang_tempcode('DECRYPTION_ERROR'), 'warn');
            return $data;
	}


	if ($htmlwrap)
	{
	    $output = do_template('COMCODE_HIDE', array('_GUID' => 'a591a0d1e6bb3dde0f22cebb9c7ab93e', 'TEXT' => 'Encrypted text ' . $id . ' (click to expand)', 'CONTENT' => $output));
	    return $output;
	}

        $output = html_to_comcode($output);
	$output = comcode_to_tempcode($output);
	if ($make_string)
		$output = $output->evaluate();

    return $output;
}

function decrypt_html($data)
{
$_data = base64_decode(remove_id(remove_magic_encryption_marker(str_replace('<br />', '', $data)), $id));
$data = '<div style="text-align: center;" id="decryptbutton_' . $id . '"><a class="button_screen_item buttons__calculate" href="#" onclick="return decrypt_it(\'' . $id . '\');">Decrypt Text</a></div><div id="decrypt_' . $id . '">' . $data . '</div>';
return do_template('COMCODE_HIDE', array('_GUID' => 'a591a0d1e6bb3dde0f22cebb9c7ab93e', 'TEXT' => 'Encrypted text ' . $id . ' (click to expand)', 'CONTENT' => $data));
}
