<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_snippet_decrypt
{
    /**
     * Run function for snippet hooks. Generates XHTML to insert into a page using AJAX.
     *
     * @return Tempcode The snippet
     */
    public function run()
    {
	//die();
        $action = post_param_string('action', 'decrypt');
        $data = post_param_string('data', '');
	$passcode = post_param_string('passcode', '');

	require_code('tempcode');
	require_code('encryption');

	if ($action == 'needspasscode')
	{
		return make_string_tempcode(needs_passcode($data));
	}

	if ($action == 'decrypt')
	{
		$decrypted = decrypt_data($data, '82f803c1875974c0c06ffd5ec1d39192', false, $passcode != '' ? $passcode : null, false);
		return $decrypted;
	}

	return;
    }
}
