<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    cns_warnings
 */

/**
 * Hook class.
 */
class Hook_warnings_punitive_demerits
{
    /**
     * Run function for displaying UI fields for this punitive action in the warnings form.
     */
    public function UI(&$hidden, &$fields)
    {
        require_code('form_templates');
        
            $member_id = get_param_integer('member_id', get_member());

            $demerits = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_40', array('mf_member_id' => $member_id));
            if ($demerits == null || $demerits == '' || !$demerits)
            $demerits = 0;
            $fields->attach(form_input_integer(do_lang_tempcode('DEMERITS'), do_lang_tempcode('DESCRIPTION_DEMERITS'), 'new_demerits', $demerits, true));
      
    }
}
