<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_AIML
{

	public function help()
	{
		return array(
		'(general chat)' => 'Talk to the bot and get a response.'
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
			curl_setopt($ch, CURLOPT_URL, "https://chatbot.lovinity.org/chatbot/conversation_start.php?bot_id=1&convo_id=" . md5('scB723sdHss723' . $userid) . "&say=" . urlencode($params[1]) . "&name=" . urlencode($username));
			$response = curl_exec($ch);
			$response2 = array();
			curl_close($ch);
			if ($response != '')
				$response2 = json_decode($response, true);
			if (is_array($response2) && array_key_exists('botsay', $response2) && $response2['botsay'] != '')
			{
				$fields = array('Lovinibot says' => $response2['botsay']);
				return array('title' => 'Chatbot', 'color' => '16777215', 'fields' => $fields);
			}
			
			return array('title' => 'Chatbot', 'color' => '16711680', 'fields' => array('ERROR' => 'Unknown error'));

	}
	
}