<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_credibility
{

	public function help()
	{
		return array(
		'!credibility|(username or user ID)' => 'Get the credibility score of the provided lovinity.org username or user ID.'
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{
		if (!array_key_exists(1,$params))
{
$fields = array(
'ERROR' => 'You need to specify a username or a user ID number to check the online status of.',
);
return array('title' => '!credibility', 'color' => '16711680', 'fields' => $fields);
}
		
		if (!is_numeric($params[1]))
			$params[1] = $GLOBALS['FORUM_DRIVER']->get_member_from_username($params[1]);

		if (is_null($params[1]))
{
$fields = array(
'ERROR' => 'The member ' . $params[1] . ' does not exist on TLC+.',
);
return array('title' => '!credibility', 'color' => '16744448', 'fields' => $fields);
}

		$credibility = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_64', array('mf_member_id' => $params[1]));
		$credibility1 = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_65', array('mf_member_id' => $params[1]));
		$credibility2 = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_66', array('mf_member_id' => $params[1]));
		$credibility3 = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_67', array('mf_member_id' => $params[1]));
		$credibility4 = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_68', array('mf_member_id' => $params[1]));
$fields = array(
'User ID' => $params[1],
'Total Credibility Score' => $credibility,
'Earned from staff' => $credibility4,
'Earned from users' => $credibility3,
'Lost from staff' => $credibility1,
'Lost from users' => $credibility2,
);
return array('title' => '!credibility', 'color' => '16744703', 'fields' => $fields);

	}
	
}