<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_killme
{
	public function help()
	{
		return array(
		'!killme' => 'Be the first to execute this command within 15 minutes or less of the TLC+ activity bot stating it sees dead people. You will earn Yang if you do, if your Discord account is linked to your lovinity.org account.',
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{
		$fields = array();
		if ($userid == '282808919162880000' || $userid == '271723210091790338')
		{
			$fields['ERROR'] = 'You little shit. How am I supposed to kill a bot?';
			return array('title' => '!killme', 'color' => '16776960', 'fields' => $fields);
		}

		require_code('rp');
		$user = rp_get_user_by_discord($userid);
		if ($user == 0 || $user == 1)
		{
			$fields['ERROR'] = 'Sorry, I cannot kill someone who has not linked their Discord account to their lovinity.org one. Do command !userid for instructions.';
			return array('title' => '!killme', 'color' => '16776960', 'fields' => $fields);
		}

		$lasttime = get_value('dead_people');
		$value = get_value('dead_people_value');

		if ((time() - $lasttime) > (60 * 15))
		{
			$fields['ERROR'] = 'Sorry, I do not see dead people at this time.';
			return array('title' => '!killme', 'color' => '16776960', 'fields' => $fields);
		}

		if ($value < 1)
		{
			$fields['ERROR'] = 'Sorry, someone else already claimed their death.';
			return array('title' => '!killme', 'color' => '16776960', 'fields' => $fields);
		}
					require_code('points2');
					system_gift_transfer('Discord server use award', $value, $user);
					$fields['KILLED'] = 'You have been killed!';
					$fields['Yang Earned'] = $value;
					set_value('dead_people_value', '0');
					return array('title' => '!killme', 'color' => '65280', 'fields' => $fields);
	}
		
}
