<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_securityscore
{
	public function help()
	{
		return array(
		'!securityscore' => 'Check the security risk scores of lovinity.org.'
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{

	$newmembers = get_value('security_score__new_members');
	$wordflag = get_value('security_score__flagged_words');
	$pagerequests = get_value('security_score__page_requests');
	$max5 = get_value('security_score__5_minute_requests');
	$failedlogins = get_value('security_score__failed_logins');
	$hackattacks = get_value('security_score__hack_attacks');
	$forgotpassword = get_value('security_score__forgot_password');
	$accessdenied = get_value('security_score__access_denied');
	$manual = get_value('security_score__manual');
	$securityscore = get_value('security_score');

	if ($securityscore < 25)
	{
	$color = 65280;
	} else if ($securityscore < 50)
	{
	$color = 16776960;
	} else if ($securityscore < 75)
	{
	$color = 16744448;
	} else if ($securityscore < 100)
	{
	$color = 16711680;
	} else {
	$color = 16777215;
	} 	

	$fields['Total Score'] = $securityscore;
	$fields['new user score'] = $newmembers;
	$fields['suspicious parameters score'] = $wordflag;
	$fields['page hits score'] = $pagerequests;
	$fields['5-min DOS score'] = $max5;
	$fields['failed logins score'] = $failedlogins;
	$fields['hack attacks score'] = $hackattacks;
	$fields['forgot password use score'] = $forgotpassword;
	$fields['access denied score'] = $accessdenied;
	$fields['manual score'] = (!is_null($manual) && $manual != '') ? $manual : 0;
	return array('title' => '!securityscore', 'color' => $color, 'fields' => $fields);

	}
	
}
