<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_social_yang
{

	public function help()
	{
		return array(
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{
		require_code('rp');
		$user = rp_get_user_by_discord($userid);
		$ceo = ($user == 2);
		if ($user === null || $user == 1 || $user == '' || $user == 0)
			return array('title' => '?yang', 'color' => '65280', 'fields' => array('result' => false));

		require_code('points2');
		system_gift_transfer('Discord server doughnuts to Yang', $params[0], $user);
			return array('title' => '?yang', 'color' => '65280', 'fields' => array('result' => true));
	}
	
}