<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_star
{
	
	public function help()
	{
		return array(
		'!star|(username or user ID)' => 'Get the STAR index (activity level) of the given lovinity.org username or ID.'
		);
	}

	public function run($params, $userid, $username = 'guest')
	{
		if (!array_key_exists(1,$params))
			{
				$fields['ERROR'] = 'You need to specify a username or user ID to check the STAR index.';
				return array('title' => '!star', 'color' => '16711680', 'fields' => $fields);
			}
		
		if (!is_numeric($params[1]))
			$params[1] = $GLOBALS['FORUM_DRIVER']->get_member_from_username($params[1]);

		if (is_null($params[1]))
			{
				$fields['ERROR'] = 'That member does not exist on TLC+.';
				return array('title' => '!star', 'color' => '16711680', 'fields' => $fields);
			}

		$star = $GLOBALS['SITE_DB']->query_select_value_if_there('f_member_custom_fields', 'field_44', array('mf_member_id' => $params[1]));

		$fields['STAR index'] = float_format($star);
		return array('title' => '!star', 'color' => '16744703', 'fields' => $fields);

	}
	
}
