<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_stats
{
	public function help()
	{
		return array(
		'!stats' => 'This command is temporarily out of service.'
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{
		die();
		    require_code('blocks/side_stats', true);
    		    $object = object_factory('Block_side_stats');
		    $stats = $object->run(array());
		    require_code('tempcode');
		    $stats = $stats->evaluate();
			
		    require_code('comcode');
		    $stats = str_replace('<ul', '<br /><br /><ul', $stats);
		    $stats = str_replace('<dd>', '<dd>: ', $stats);
		    $stats = str_replace('<dt>', '<br /><dt>', $stats);
		    $stats = html_to_comcode($stats, true);
		    $stats = strip_comcode($stats);
		    return $stats;

	}
	
}