<?php /*

 Composr
 Copyright (c) ocProducts, 2004-2016

 See text/EN/licence.txt for full licencing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  ocProducts Ltd
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_discord_suspicious
{

	public function help()
	{
		return array(
		'!suspicious|(score)|(description)' => 'Add a manual security risk score entry that will be effective for 24 hours. Only Lovinity can use this command.'
		);
	}
	
	public function run($params, $userid, $username = 'guest')
	{
		
		if (!array_key_exists(1,$params) || !array_key_exists(2,$params))
			{
				$fields['ERROR'] = 'This command requires parameters SCORE and DESCRIPTION.';
				return array('title' => '!suspicious', 'color' => '16711680', 'fields' => $fields);
			}

		require_code('rp');

		$user = rp_get_user_by_discord($userid);
		if ($user != 2)
			{
				$fields['ERROR'] = 'Only Lovinity can use this command.';
				return array('title' => '!suspicious', 'color' => '16711680', 'fields' => $fields);
			}

	$GLOBALS['SITE_DB']->query_insert('suspicious', array(
            'description' => $params[2],
            'score' => $params[1],
            'timestamp' => time()
    ));	
		
		$fields['Results'] = 'Entry added.';
		return array('title' => '!suspicious', 'color' => '65280', 'fields' => $fields);
	}
	
}
